workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  containerSpec:
    imageUri: gcr.io/dtumlops-484812/rnn-trainer:latest
    command: ["uv", "run", "python", "-u", "src/models/train_rnn.py"]
    args:
    - model_type=lstm
    - epochs=5
    - data_path=/gcs/mlops-dataset-84636/data/grouped
    env:
    - name: GCS_MODEL_BUCKET
      value: mlops-dataset-84636
    - name: GCS_MODEL_PATH
      value: models
